const chars=[{id:'gran',name:'Gran',tag:'C / blade',icon:'G',color:'#3979bd',d:12,rate:620,range:1.7,k:'spin',cost:4},{id:'io',name:'Io',tag:'C / bolt',icon:'I',color:'#886bc9',d:17,rate:800,range:4.2,k:'shot',cost:5},{id:'zeta',name:'Zeta',tag:'UC / twin spear',icon:'Z',color:'#d45747',d:31,rate:520,range:2.3,k:'spin2',cost:8},{id:'luria',name:'Lyria',tag:'UC / support',icon:'L',color:'#3f92be',d:0,rate:3300,range:2.45,k:'support',cost:8},{id:'haaselia',name:'Haaselia',tag:'R / wide water',icon:'H',color:'#3c7ea9',d:13,rate:1100,range:4.8,k:'area',cost:15}];
const stages=[{name:'1-1 Azure Gate',waves:8,hp:50,count:7,speed:1.08},{name:'1-2 Sky Valley',waves:10,hp:98,count:8,speed:1.22},{name:'1-3 Astral Shadow',waves:12,hp:165,count:9,speed:1.36}];
const route=[3,10,17,18,19,26,33,32,31,30,29,36,43,44,45,46,47,54,61,60,59,66];
const $=id=>document.getElementById(id),slots=[],s={stage:0,wave:0,mana:0,base:100,kills:0,units:[],enemies:[],queue:[],selected:[],pending:null,paused:false,running:true,serial:1,summons:0,last:performance.now(),won:false};
const unitLayer=$('unitLayer'),enemyLayer=$('enemyLayer'),fx=$('projectileLayer');let audio;
function tone(freq,duration=.06,volume=.035){try{audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.value=volume;o.connect(g).connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.stop(audio.currentTime+duration)}catch{}}
function text(t){$('hint').textContent=t}function cash(){$('mana').textContent=Math.floor(s.mana);$('summonCost').textContent=s.pending?'CANCEL':'SELECT'}function grid(i){return{x:i%7,y:Math.floor(i/7)}}function center(i){let p=grid(i);return{x:(p.x+.5)/7*100,y:(p.y+.5)/10*100}}
function routePos(v){let a=Math.max(0,Math.min(route.length-.001,v)),i=Math.floor(a),t=a-i,p=grid(route[i]),q=grid(route[i+1]);return{gx:p.x+(q.x-p.x)*t,gy:p.y+(q.y-p.y)*t,x:(p.x+.5+(q.x-p.x)*t)/7*100,y:(p.y+.5+(q.y-p.y)*t)/10*100}}
function build(){for(let i=0;i<70;i++){let el=document.createElement('div'),road=route.includes(i);el.className='slot '+(road?'roadcell':'');el.dataset.slot=i;el.onclick=()=>clickCell(i);unitLayer.append(el);slots.push(el)}$('unitGuide').innerHTML=chars.map(c=>`<button class="guide-card" data-char="${c.id}"><b>${c.icon} ${c.name}</b><span>${c.tag}</span><small>* ${c.cost}</small></button>`).join('');document.querySelectorAll('[data-char]').forEach(e=>e.onclick=()=>choose(chars.find(c=>c.id===e.dataset.char)))}
function choose(char){if(s.pending)cancel();if(s.units.length>=70-route.length)return text('No free tiles. Merge or move a unit.');let free=s.units.length===0&&(char.id==='gran'||char.id==='io'),price=free?0:char.cost;if(s.mana<price)return text('Not enough stars for '+char.name+'.');s.mana-=price;s.summons++;s.pending=char;tone(440,.06);slots.forEach((e,i)=>{if(!route.includes(i)&&!s.units.some(u=>u.slot===i))e.classList.add('deployable')});cash();text((free?'Free ':('* '+price+' '))+char.name+': choose a glowing square.')}
function cancel(){s.pending=null;slots.forEach(e=>e.classList.remove('deployable'));cash();text('Deployment cancelled.')}
function clickCell(i){if(route.includes(i))return;if(s.pending){if(!s.units.some(u=>u.slot===i)){create(i,s.pending);cancel()}return}let u=s.units.find(x=>x.slot===i);if(!u&&s.selected.length===1){let one=s.units.find(x=>x.id===s.selected[0]);one.slot=i;slots[i].append(one.el);s.selected=[];paint();text('Unit moved.');return}if(u)pick(u)}
function create(slot,char,star=1){let u={id:s.serial++,slot,char,star,last:0,buff:0},el=document.createElement('div');u.el=el;el.className='unit';el.style.setProperty('--accent',char.color);el.style.setProperty('--orb',char.id==='zeta'?'#ffbd67':'#ffe177');el.innerHTML=`<span class="portrait">${char.icon}</span><span class="unit-name">${char.name}</span><span class="star">${'*'.repeat(star)}</span>`;let n=char.k==='spin'?1:char.k==='spin2'?2:0;for(let i=0;i<n;i++)el.insertAdjacentHTML('beforeend',`<i class="orbiter" style="--speed:${n===2?'.65s':'1s'};animation-delay:-${i*.32}s"></i>`);el.onclick=e=>{e.stopPropagation();pick(u)};slots[slot].append(el);s.units.push(u);text(char.name+' deployed.');if(s.wave===0)setTimeout(wave,400)}
function pick(u){if(s.selected.includes(u.id))s.selected=s.selected.filter(id=>id!==u.id);else{s.selected.length===2&&s.selected.shift();s.selected.push(u.id)}paint();s.selected.length===2?mergeBox():text('Choose another unit to merge, or an empty square to move.')}
function paint(){slots.forEach(e=>e.classList.remove('selected'));s.selected.forEach(id=>{let u=s.units.find(x=>x.id===id);u&&slots[u.slot].classList.add('selected')})}
function mergeBox(){let[a,b]=s.selected.map(id=>s.units.find(u=>u.id===id)),safe=a.star+b.star,risk=safe+1,ch=Math.max(20,76-(safe-2)*9);$('modalCard').innerHTML=`<h2>MERGE</h2><p>${a.char.name} *${a.star} + ${b.char.name} *${b.star}</p><button class="safe" data-x="safe">Safe: *${safe}<small>100% success</small></button><button class="risk" data-x="risk">Risk: *${risk}<small>${ch}% / failure loses both</small></button><br><button data-x="cancel">Cancel</button>`;$('modal').classList.remove('hidden');document.querySelectorAll('[data-x]').forEach(e=>e.onclick=()=>merge(e.dataset.x))}
function merge(mode){if(mode==='cancel'){close();return}let[a,b]=s.selected.map(id=>s.units.find(u=>u.id===id)),total=a.star+b.star,ch=Math.max(20,76-(total-2)*9),slot=b.slot,char=b.char;remove(a);remove(b);if(mode==='risk'&&Math.random()*100>=ch){text('Merge failed. Both units were lost.');burst(50,55,'#e3586d')}else{create(slot,char,total+(mode==='risk'?1:0));text('Merge success: result remains on the second selected tile.');burst(center(slot).x,center(slot).y,'#fff080')}s.selected=[];close()}
function remove(u){u.el.remove();s.units=s.units.filter(x=>x!==u)}function close(){$('modal').classList.add('hidden');paint()}
function enemyType(i){if(s.stage===0)return s.wave>=6&&i%5===4?'armor':'normal';if(s.stage===1)return i%5===0?'fast':i%5===3?'armor':'normal';return i%6===0?'fast':i%6===2||i%6===3?'swarm':i%6===5?'armor':'normal'}
function wave(){let st=stages[s.stage];if(s.wave>=st.waves)return;s.wave++;let n=st.count+Math.floor(s.wave*.8),hp=Math.round(st.hp*Math.pow(1.255,s.wave-1));for(let i=0;i<n;i++)s.queue.push({at:performance.now()+i*(s.stage===2?520:700),hp,boss:false,type:enemyType(i)});if(s.wave===st.waves)s.queue.push({at:performance.now()+n*720,hp:Math.round(hp*8),boss:true,type:'boss'});notice('WAVE '+s.wave);hud()}
function spawn(d){let type=d.type,hp=d.hp,spd=stages[s.stage].speed,reward=3+Math.floor((s.wave-1)/3);if(type==='fast'){hp=Math.round(hp*.64);spd*=1.7;reward+=1}else if(type==='armor'){hp=Math.round(hp*2.0);spd*=.68;reward+=3}else if(type==='swarm'){hp=Math.round(hp*.52);spd*=1.12;reward=Math.max(2,reward-1)}let e={id:s.serial++,p:-.5,hp:d.boss?d.hp:hp,max:d.boss?d.hp:hp,speed:spd*(d.boss?.57:1),boss:d.boss,reward:d.boss?32:reward,type};let el=document.createElement('div');el.className='enemy '+(e.boss?'boss':'');el.style.setProperty('--enemy',e.boss?'#70395c':type==='fast'?'#c06e5a':type==='armor'?'#555d77':type==='swarm'?'#9c5f9a':'#7e4d86');el.innerHTML=(e.boss?'B':type==='fast'?'F':type==='armor'?'A':type==='swarm'?'S':'')+'<span class="enemy-hp"><i></i></span>';e.el=el;enemyLayer.append(el);s.enemies.push(e)}
function moveEnemies(dt){let now=performance.now();while(s.queue[0]?.at<=now)spawn(s.queue.shift());s.enemies.slice().forEach(e=>{e.p+=e.speed*dt/1000;let p=routePos(e.p);Object.assign(e,p);e.el.style.left=p.x+'%';e.el.style.top=p.y+'%';if(e.p>=route.length-1){damage(e.boss?22:8);kill(e,false)}})}
function power(u){return u.char.d*Math.pow(2.05,u.star-1)*(u.buff>performance.now()?1.55:1)}function attack(){let now=performance.now();s.units.forEach(u=>{let c=u.char;if(now-u.last<c.rate)return;u.last=now;if(c.k==='support'){let from=grid(u.slot),allies=s.units.filter(x=>Math.hypot(grid(x.slot).x-from.x,grid(x.slot).y-from.y)<=c.range);allies.forEach(x=>x.buff=now+3000);s.base=Math.min(100,s.base+5+u.star*2);u.el.classList.add('casting');setTimeout(()=>u.el&&u.el.classList.remove('casting'),500);burst(center(u.slot).x,center(u.slot).y,'#79fff0');text('Lyria: '+allies.length+' nearby allies boosted and base healed.');return}let from=grid(u.slot),targets=s.enemies.filter(e=>Math.hypot(e.gx-from.x,e.gy-from.y)<=c.range);if(!targets.length)return;if(c.k==='area'){targets.forEach(e=>hit(e,power(u)*.55,'#8eefff'));burst(center(u.slot).x,center(u.slot).y,'#8eefff')}else{let e=targets.sort((a,b)=>b.p-a.p)[0];if(c.k==='spin'||c.k==='spin2')hit(e,power(u),c.k==='spin2'?'#ffbd67':'#fff080');else shot(center(u.slot),e,power(u),c.color)}})}
function shot(from,e,d,col){let p=document.createElement('i');p.className='projectile';p.style.setProperty('--shot',col);fx.append(p);let t0=performance.now();function go(n){let t=Math.min(1,(n-t0)/220);p.style.left=(from.x+(e.x-from.x)*t)+'%';p.style.top=(from.y+(e.y-from.y)*t)+'%';if(t<1&&s.enemies.includes(e))requestAnimationFrame(go);else{p.remove();s.enemies.includes(e)&&hit(e,d,col)}}requestAnimationFrame(go)}
function hit(e,d,col){e.hp-=d;tone(180+Math.min(260,d*2),.035,.018);e.el.querySelector('i').style.width=Math.max(0,e.hp/e.max*100)+'%';e.el.style.transform='scale(1.24)';burst(e.x,e.y,col);setTimeout(()=>e.el&&(e.el.style.transform=''),70);e.hp<=0&&kill(e,true)}
function kill(e,reward){e.el.remove();s.enemies=s.enemies.filter(x=>x!==e);if(reward){s.kills++;s.mana+=e.reward;cash();burst(e.x,e.y,e.boss?'#ffcd62':'#f7b9ff')}if(!s.queue.length&&!s.enemies.length){s.wave<stages[s.stage].waves?setTimeout(wave,850):win()}hud()}function damage(n){s.base=Math.max(0,s.base-n);hud();if(!s.base)lose()}function burst(x,y,col){let p=document.createElement('i');p.className='projectile';p.style.cssText=`left:${x}%;top:${y}%;--shot:${col};width:18px;height:18px;opacity:.95;transition:.25s`;fx.append(p);requestAnimationFrame(()=>{p.style.transform='scale(2.7)';p.style.opacity='0'});setTimeout(()=>p.remove(),280)}
function hud(){let st=stages[s.stage];$('stageName').textContent=st.name;$('wave').textContent=s.wave;$('waveMax').textContent=st.waves;$('kills').textContent=s.kills;$('enemiesLeft').textContent=s.enemies.length+s.queue.length;$('baseHp').textContent=Math.ceil(s.base);$('baseBar').style.width=s.base+'%'}function notice(t){let n=$('waveNotice');n.textContent=t;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),1000)}function win(){if(s.won)return;s.won=true;let nx=s.stage<2;$('modalCard').innerHTML=`<h2>STAGE CLEAR</h2><p>Defeated: ${s.kills}</p><button id="next">${nx?'Next stage':'Play again'}</button>`;$('modal').classList.remove('hidden');$('next').onclick=()=>reset(nx?s.stage+1:0)}function lose(){s.running=false;$('modalCard').innerHTML='<h2>BASE FALLEN</h2><p>Use corners for close attacks and long lines for ranged units.</p><button id="retry">Retry</button>';$('modal').classList.remove('hidden');$('retry').onclick=()=>reset(s.stage)}
function reset(stage){s.stage=stage;s.wave=0;s.mana=0;s.base=100;s.kills=0;s.units.forEach(u=>u.el.remove());s.enemies.forEach(e=>e.el.remove());s.units=[];s.enemies=[];s.queue=[];s.selected=[];s.pending=null;s.summons=0;s.running=true;s.won=false;close();cash();hud();notice('DEPLOY FIRST UNIT')}function loop(now){let dt=now-s.last;s.last=now;if(s.running&&!s.paused){moveEnemies(dt);attack()}requestAnimationFrame(loop)}
$('summonBtn').onclick=()=>s.pending?cancel():text('Choose a character card below.');$('pauseBtn').onclick=()=>{s.paused=!s.paused;$('pauseBtn').textContent=s.paused?'PLAY':'PAUSE';text(s.paused?'Paused.':'Battle resumed.')};build();reset(0);requestAnimationFrame(loop);
