const chars=[
 {id:'gran',name:'Gran',tag:'C / blade',icon:'G',color:'#3979bd',damage:12,rate:620,range:31,kind:'spin'},
 {id:'io',name:'Io',tag:'C / bolt',icon:'I',color:'#886bc9',damage:17,rate:800,range:43,kind:'shot'},
 {id:'zeta',name:'Zeta',tag:'UC / twin spear',icon:'Z',color:'#d45747',damage:31,rate:520,range:36,kind:'spin2'},
 {id:'luria',name:'Lyria',tag:'UC / support',icon:'L',color:'#3f92be',damage:0,rate:3600,range:0,kind:'support'},
 {id:'haaselia',name:'Haaselia',tag:'R / wide water',icon:'H',color:'#3c7ea9',damage:13,rate:1100,range:54,kind:'area'}
];
const stages=[{name:'1-1 Azure Gate',waves:8,hp:44,count:7,speed:5.4},{name:'1-2 Sky Valley',waves:10,hp:72,count:8,speed:6.2},{name:'1-3 Astral Shadow',waves:12,hp:105,count:9,speed:7.1}];
const pads=[{x:18,y:17},{x:77,y:17},{x:18,y:38},{x:80,y:43},{x:16,y:62},{x:77,y:67},{x:20,y:82},{x:80,y:84}];
const waypoints=[{x:50,y:-6},{x:22,y:8},{x:77,y:18},{x:55,y:29},{x:20,y:42},{x:43,y:53},{x:82,y:64},{x:57,y:76},{x:20,y:90},{x:50,y:105}];
const $=id=>document.getElementById(id),slots=[],state={stage:0,wave:0,mana:0,base:100,kills:0,units:[],enemies:[],queue:[],selected:[],pending:null,paused:false,running:true,serial:1,summons:0,last:performance.now(),won:false};
const unitLayer=$('unitLayer'),enemyLayer=$('enemyLayer'),projectileLayer=$('projectileLayer');
function msg(t){$('hint').textContent=t} function cost(){return 4+Math.floor(state.summons/4)*2} function money(){ $('mana').textContent=Math.floor(state.mana);$('summonCost').textContent=state.summons===0?'FREE':'* '+cost() }
function pos(progress){let scaled=Math.max(0,Math.min(.999,progress))*(waypoints.length-1),i=Math.floor(scaled),t=scaled-i,a=waypoints[i],b=waypoints[i+1];return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}}
function setup(){pads.forEach((p,i)=>{let s=document.createElement('div');s.className='slot';s.dataset.slot=i;s.style.left=p.x+'%';s.style.top=p.y+'%';s.onclick=()=>slotClick(i);unitLayer.append(s);slots.push(s)});$('unitGuide').innerHTML=chars.map(c=>`<div class="guide-card"><b>${c.icon} ${c.name}</b><span>${c.tag}</span></div>`).join('')}
function randomChar(){let r=Math.random();return r<.7?chars[(Math.random()*2)|0]:r<.94?chars[2+((Math.random()*2)|0)]:chars[4]}
function summon(){if(state.pending){cancelDeploy();return}let c=cost();if(state.summons&&state.mana<c){msg('Not enough stars. Defeat enemies first.');return}if(state.units.length===pads.length){msg('All pads are occupied. Merge or move a unit.');return}if(state.summons)state.mana-=c;state.summons++;state.pending=randomChar();slots.forEach(s=>{if(!state.units.some(u=>u.slot===+s.dataset.slot))s.classList.add('deployable')});money();msg('Choose a glowing pad to deploy '+state.pending.name+'.')}
function cancelDeploy(){state.pending=null;slots.forEach(s=>s.classList.remove('deployable'));msg('Deployment cancelled.')}
function slotClick(slot){if(state.pending){if(state.units.some(u=>u.slot===slot))return;createUnit(slot,state.pending);cancelDeploy();return}let occupied=state.units.find(u=>u.slot===slot);if(!occupied&&state.selected.length===1){let u=state.units.find(x=>x.id===state.selected[0]);moveUnit(u,slot);state.selected=[];paintSelection();msg('Unit moved.');return}if(occupied)select(occupied)}
function createUnit(slot,char,star=1){let u={id:state.serial++,slot,char,star,last:0,buff:0};state.units.push(u);let e=document.createElement('div');e.className='unit';e.style.setProperty('--accent',char.color);e.style.setProperty('--orb',char.id==='zeta'?'#ffbd67':'#ffe177');e.innerHTML=`<span class="portrait">${char.icon}</span><span class="unit-name">${char.name}</span><span class="star">${'*'.repeat(star)}</span>`;let blades=char.kind==='spin'?1:char.kind==='spin2'?2:0;for(let i=0;i<blades;i++)e.insertAdjacentHTML('beforeend',`<i class="orbiter" style="--speed:${char.kind==='spin2'?'.65s':'1s'};animation-delay:-${i*.32}s"></i>`);e.onclick=ev=>{ev.stopPropagation();select(u)};slots[slot].append(e);u.el=e;msg(char.name+' deployed.');}
function moveUnit(u,slot){u.slot=slot;slots[slot].append(u.el)}
function select(u){if(state.selected.includes(u.id))state.selected=state.selected.filter(id=>id!==u.id);else{if(state.selected.length===2)state.selected.shift();state.selected.push(u.id)}paintSelection();if(state.selected.length===2)mergeDialog();else msg('Select another unit to merge, or tap an empty pad to move it.')}
function paintSelection(){slots.forEach(s=>s.classList.remove('selected'));state.selected.forEach(id=>{let u=state.units.find(x=>x.id===id);if(u)slots[u.slot].classList.add('selected')})}
function mergeDialog(){let [a,b]=state.selected.map(id=>state.units.find(u=>u.id===id)),safe=a.star+b.star,risky=safe+1,chance=Math.max(20,76-(safe-2)*9);$('modalCard').innerHTML=`<h2>MERGE</h2><p>${a.char.name} *${a.star} + ${b.char.name} *${b.star}</p><button class="safe" data-m="safe">Safe: *${safe}<small>100% success</small></button><button class="risk" data-m="risk">Risk: *${risky}<small>${chance}% / failure loses both</small></button><br><button data-m="cancel">Cancel</button>`;$('modal').classList.remove('hidden');document.querySelectorAll('[data-m]').forEach(x=>x.onclick=()=>merge(x.dataset.m))}
function merge(mode){if(mode==='cancel'){close();return}let [a,b]=state.selected.map(id=>state.units.find(u=>u.id===id)),sum=a.star+b.star,chance=Math.max(20,76-(sum-2)*9),slot=a.slot,strong=a.char.damage>=b.char.damage?a.char:b.char;remove(a);remove(b);if(mode==='risk'&&Math.random()*100>=chance){msg('Merge failed. Both units were lost.');burst(50,55,'#e3586d')}else{createUnit(slot,strong,sum+(mode==='risk'?1:0));msg('Merge success! '+strong.name+' became stronger.');burst(50,55,'#fff080')}state.selected=[];close()}
function remove(u){u.el.remove();state.units=state.units.filter(x=>x!==u)} function close(){$('modal').classList.add('hidden');paintSelection()}
function startWave(){let s=stages[state.stage];if(state.wave>=s.waves)return;state.wave++;let n=s.count+Math.floor(state.wave*.7);for(let i=0;i<n;i++)state.queue.push({at:performance.now()+i*700,hp:Math.round(s.hp*Math.pow(1.21,state.wave-1)),boss:false});if(state.wave===s.waves)state.queue.push({at:performance.now()+n*720,hp:Math.round(s.hp*Math.pow(1.21,state.wave)*7),boss:true});notice('WAVE '+state.wave);hud()}
function spawn(data){let e={id:state.serial++,p:-.03,hp:data.hp,max:data.hp,speed:stages[state.stage].speed*(data.boss?.57:1),boss:data.boss,reward:data.boss?28:3+Math.floor((state.wave-1)/4)};let el=document.createElement('div');el.className='enemy '+(e.boss?'boss':'');el.style.setProperty('--enemy',e.boss?'#70395c':'#7e4d86');el.innerHTML=(e.boss?'B':'')+'<span class="enemy-hp"><i></i></span>';enemyLayer.append(el);e.el=el;state.enemies.push(e)}
function enemies(dt){let now=performance.now();while(state.queue[0]?.at<=now)spawn(state.queue.shift());state.enemies.slice().forEach(e=>{e.p+=e.speed*dt/1000/100;let q=pos(e.p);e.x=q.x;e.y=q.y;e.el.style.left=q.x+'%';e.el.style.top=q.y+'%';if(e.p>=1){hurt(e.boss?22:8);kill(e,false)}})}
function power(u){return u.char.damage*Math.pow(2.05,u.star-1)*(u.buff>performance.now()?1.4:1)}
function attacks(){let now=performance.now();state.units.forEach(u=>{let c=u.char;if(now-u.last<c.rate)return;u.last=now;if(c.kind==='support'){state.units.forEach(x=>x.buff=now+2700);state.base=Math.min(100,state.base+7+u.star*2);msg('Lyria boosts the party and restores the base.');return}let from=pads[u.slot],targets=state.enemies.filter(e=>Math.hypot(e.x-from.x,e.y-from.y)<=c.range);if(!targets.length)return;if(c.kind==='area'){targets.forEach(e=>hit(e,power(u)*.55));burst(from.x,from.y,'#8eefff')}else{let target=targets.sort((a,b)=>b.p-a.p)[0];shot(from,target,power(u),c.color)}})}
function shot(from,target,dmg,color){let e=document.createElement('i');e.className='projectile';e.style.setProperty('--shot',color);projectileLayer.append(e);let start=performance.now();function go(now){let t=Math.min(1,(now-start)/220);e.style.left=(from.x+(target.x-from.x)*t)+'%';e.style.top=(from.y+(target.y-from.y)*t)+'%';if(t<1&&state.enemies.includes(target))requestAnimationFrame(go);else{e.remove();if(state.enemies.includes(target))hit(target,dmg)}}requestAnimationFrame(go)}
function hit(e,dmg){e.hp-=dmg;e.el.querySelector('i').style.width=Math.max(0,e.hp/e.max*100)+'%';e.el.style.transform='scale(1.22)';setTimeout(()=>{if(e.el)e.el.style.transform=''},70);if(e.hp<=0)kill(e,true)}
function kill(e,reward){e.el.remove();state.enemies=state.enemies.filter(x=>x!==e);if(reward){state.kills++;state.mana+=e.reward;money();burst(e.x,e.y,e.boss?'#ffcd62':'#f7b9ff')}if(!state.queue.length&&!state.enemies.length){if(state.wave<stages[state.stage].waves)setTimeout(startWave,850);else win()}hud()}
function hurt(n){state.base=Math.max(0,state.base-n);hud();if(!state.base)lose()}function burst(x,y,color){let p=document.createElement('i');p.className='projectile';p.style.cssText=`left:${x}%;top:${y}%;--shot:${color};width:20px;height:20px;opacity:.95;transition:.35s;`;projectileLayer.append(p);requestAnimationFrame(()=>{p.style.transform='scale(3)';p.style.opacity='0'});setTimeout(()=>p.remove(),400)}
function hud(){let s=stages[state.stage];$('stageName').textContent=s.name;$('wave').textContent=state.wave;$('waveMax').textContent=s.waves;$('kills').textContent=state.kills;$('enemiesLeft').textContent=state.enemies.length+state.queue.length;$('baseHp').textContent=Math.ceil(state.base);$('baseBar').style.width=state.base+'%'}function notice(t){let n=$('waveNotice');n.textContent=t;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),1000)}
function win(){if(state.won)return;state.won=true;let next=state.stage<2;$('modalCard').innerHTML=`<h2>STAGE CLEAR</h2><p>Defeated: ${state.kills}</p><button id="next">${next?'Next stage':'Play again'}</button>`;$('modal').classList.remove('hidden');$('next').onclick=()=>reset(next?state.stage+1:0)}function lose(){state.running=false;$('modalCard').innerHTML='<h2>BASE FALLEN</h2><p>Build higher stars with merges, then try again.</p><button id="retry">Retry</button>';$('modal').classList.remove('hidden');$('retry').onclick=()=>reset(state.stage)}
function reset(stage){state.stage=stage;state.wave=0;state.mana=0;state.base=100;state.kills=0;state.units.forEach(u=>u.el.remove());state.enemies.forEach(e=>e.el.remove());state.units=[];state.enemies=[];state.queue=[];state.selected=[];state.pending=null;state.summons=0;state.running=true;state.won=false;close();money();hud();notice('BATTLE START');setTimeout(startWave,700)}function loop(now){let dt=now-state.last;state.last=now;if(state.running&&!state.paused){enemies(dt);attacks()}requestAnimationFrame(loop)}
$('summonBtn').onclick=summon;$('pauseBtn').onclick=()=>{state.paused=!state.paused;$('pauseBtn').textContent=state.paused?'PLAY':'PAUSE';msg(state.paused?'Paused.':'Battle resumed.')};setup();reset(0);requestAnimationFrame(loop);
