const characters = [
  { id:'gran', name:'グラン', rarity:'C', icon:'⚔', accent:'#3979bd', role:'旋回剣', base:11, rate:650, range:78, orb:'#ffe177', desc:'近距離の安定火力' },
  { id:'io', name:'イオ', rarity:'C', icon:'✦', accent:'#886bc9', role:'魔法弾', base:15, rate:900, range:245, orb:'#d9a7ff', desc:'遠距離の単体攻撃' },
  { id:'zeta', name:'ゼタ', rarity:'UC', icon:'♜', accent:'#d45747', role:'双槍旋回', base:27, rate:540, range:121, orb:'#ffbd67', desc:'広めの近距離火力' },
  { id:'luria', name:'ルリア', rarity:'UC', icon:'✧', accent:'#3f92be', role:'加護', base:0, rate:4200, range:0, orb:'#8ffff5', desc:'味方強化・拠点回復' },
  { id:'haaselia', name:'ハーゼリーラ', rarity:'R', icon:'☾', accent:'#3c7ea9', role:'水界', base:10, rate:1300, range:270, orb:'#86e5ff', desc:'広域連続ダメージ' }
];
const stages = [
  {name:'1-1 蒼空の門', waves:8, enemyHp:60, count:6, speed:18, bonus:0},
  {name:'1-2 浮島の峡谷', waves:10, enemyHp:90, count:7, speed:22, bonus:9},
  {name:'1-3 星晶獣の影', waves:12, enemyHp:120, count:8, speed:25, bonus:20}
];
const $ = id => document.getElementById(id);
const state = {stage:0, wave:0, mana:0, base:100, kills:0, units:[], enemies:[], selected:[], spawnQueue:[], paused:false, running:true, summonCount:0, nextId:1, last:performance.now(), stageWon:false};
const slots = []; const battlefield = $('battlefield'); const unitLayer = $('unitLayer'); const enemyLayer = $('enemyLayer'); const projectileLayer = $('projectileLayer');

function save(){ localStorage.setItem('skyMergeDefense', JSON.stringify({unlocked: Math.max(+localStorage.getItem('skyMergeUnlocked')||0,state.stage)})); }
function setupBoard(){ for(let i=0;i<9;i++){const slot=document.createElement('div');slot.className='slot';slot.dataset.slot=i;slot.addEventListener('click',()=>selectUnit(slot.dataset.slot));unitLayer.append(slot);slots.push(slot);} }
function guide(){ $('unitGuide').innerHTML=characters.map(c=>`<div class="guide-card"><b>${c.icon} ${c.name}</b><span>${c.rarity}・${c.role}</span><small>${c.desc}</small></div>`).join(''); }
function currency(){ $('mana').textContent=Math.floor(state.mana); const cost=summonCost(); $('summonCost').textContent=state.summonCount===0?'無料':`✦ ${cost}`; }
function summonCost(){return 8+Math.floor(state.summonCount/3)*3;}
function unitPower(u){ return u.character.base * Math.pow(2.05,u.star-1) * (u.buffUntil>performance.now()?1.38:1); }
function makeUnit(slotIndex, forced){ const free=state.summonCount===0; const cost=summonCost(); if(!forced&&!free&&state.mana<cost){hint('✦が足りません。敵を倒して集めよう！');return;} if(!forced&&!free)state.mana-=cost; if(!forced)state.summonCount++; const pool=Math.random()<.69?characters.slice(0,2):Math.random()<.84?characters.slice(2,4):characters.slice(4); const char=forced||pool[Math.floor(Math.random()*pool.length)]; const u={id:state.nextId++,slot:+slotIndex,character:char,star:1,lastAttack:0,buffUntil:0};state.units.push(u);renderUnit(u);currency();hint(`${char.name} ★1 を召喚！`); }
function renderUnit(u){const el=document.createElement('div');el.className='unit';el.dataset.id=u.id;el.style.setProperty('--accent',u.character.accent);el.style.setProperty('--orb',u.character.orb);el.innerHTML=`<span class="portrait">${u.character.icon}</span><span class="unit-name">${u.character.name}</span><span class="star">${'★'.repeat(Math.min(u.star,6))}</span>`;if(['gran','zeta'].includes(u.character.id)) for(let x=0;x<(u.character.id==='zeta'?2:1);x++)el.insertAdjacentHTML('beforeend',`<i class="orbiter" style="--speed:${u.character.id==='zeta'?'.72s':'1s'};animation-delay:-${x*.36}s"></i>`);el.addEventListener('click',e=>{e.stopPropagation();selectUnit(u.slot);});slots[u.slot].append(el);u.el=el;}
function refreshUnits(){ state.units.forEach(u=>{u.el.classList.toggle('buff',u.buffUntil>performance.now());u.el.querySelector('.star').textContent='★'.repeat(Math.min(u.star,6));}); }
function selectUnit(slot){const u=state.units.find(x=>x.slot===+slot);if(!u)return;if(state.selected.includes(u.id))state.selected=state.selected.filter(id=>id!==u.id);else{if(state.selected.length===2)state.selected.shift();state.selected.push(u.id);} slots.forEach(s=>s.classList.remove('selected'));state.selected.forEach(id=>slots[state.units.find(u=>u.id===id).slot].classList.add('selected')); if(state.selected.length===2)showMerge();else hint('もう1体選ぶと合成できます');}
function showMerge(){const [a,b]=state.selected.map(id=>state.units.find(u=>u.id===id));const safe=a.star+b.star;const risky=safe+1;const chance=Math.max(20,76-(safe-2)*9);$('modalCard').innerHTML=`<h2>進化合成</h2><p><b>${a.character.name} ★${a.star}</b> ＋ <b>${b.character.name} ★${b.star}</b></p><button class="safe" data-merge="safe">安全進化：★${safe}<small>成功率 100%</small></button><button class="risk" data-merge="risk">確率進化：★${risky}<small>成功率 ${chance}%／失敗で完全ロスト</small></button><br><button data-merge="cancel">キャンセル</button>`;$('modal').classList.remove('hidden');document.querySelectorAll('[data-merge]').forEach(b=>b.onclick=()=>merge(b.dataset.merge));}
function merge(mode){if(mode==='cancel'){closeModal();return}const [a,b]=state.selected.map(id=>state.units.find(u=>u.id===id));if(!a||!b)return;const total=a.star+b.star;const chance=Math.max(20,76-(total-2)*9);removeUnit(a);removeUnit(b);if(mode==='risk'&&Math.random()*100>=chance){hint('進化失敗…素材は星の海へ消えた');burst(50,70,'#e3586d');}else{const star=total+(mode==='risk'?1:0); const strong=a.character.base>=b.character.base?a.character:b.character; const open=slots.findIndex(s=>!state.units.some(u=>u.slot===+s.dataset.slot)); const u={id:state.nextId++,slot:open<0?a.slot:open,character:strong,star,lastAttack:0,buffUntil:0};state.units.push(u);renderUnit(u);hint(`${strong.name} が ★${star} に進化！`);burst(50,70,'#fff080');}state.selected=[];closeModal();}
function removeUnit(u){u.el.remove();state.units=state.units.filter(x=>x!==u)}function closeModal(){$('modal').classList.add('hidden');slots.forEach(s=>s.classList.remove('selected'));}
function startWave(){const s=stages[state.stage];if(state.wave>=s.waves)return;state.wave++;const count=s.count+Math.floor(state.wave*.65);for(let i=0;i<count;i++)state.spawnQueue.push({at:performance.now()+i*480,hp:Math.round(s.enemyHp*Math.pow(1.25,state.wave-1)),boss:false});if(state.wave===s.waves)state.spawnQueue.push({at:performance.now()+count*500+400,hp:Math.round(s.enemyHp*Math.pow(1.25,state.wave)*8),boss:true});notice(`WAVE ${state.wave}`);updateHud();}
function createEnemy(data){const e={id:state.nextId++,x:55+Math.random()*38,y:-8,hp:data.hp,maxHp:data.hp,speed:stages[state.stage].speed*(data.boss?.58:1)*(0.9+Math.random()*.2),boss:data.boss,reward:data.boss?18+state.wave*3:Math.max(2,Math.ceil(data.hp/45))};const el=document.createElement('div');el.className=`enemy ${e.boss?'boss':''}`;el.style.setProperty('--enemy',e.boss?'#70395c':'#7e4d86');el.innerHTML=`${e.boss?'♛':''}<span class="enemy-hp"><i></i></span>`;enemyLayer.append(el);e.el=el;state.enemies.push(e);}
function updateEnemies(dt){const now=performance.now();while(state.spawnQueue[0]?.at<=now)createEnemy(state.spawnQueue.shift());state.enemies.slice().forEach(e=>{e.y+=e.speed*dt/1000;e.el.style.left=e.x+'%';e.el.style.top=e.y+'%';if(e.y>=92){damageBase(e.boss?22:9);destroyEnemy(e,false);}});}
function attack(dt){const now=performance.now();state.units.forEach(u=>{const c=u.character;if(now-u.lastAttack<c.rate)return;u.lastAttack=now;if(c.id==='luria'){state.units.forEach(x=>x.buffUntil=now+2600);state.base=Math.min(100,state.base+6+u.star*2);hint('ルリアの加護！ 味方を強化、拠点を回復');return;}const targets=state.enemies.filter(e=>{const pos=slotPosition(u.slot);return Math.hypot(e.x-pos.x,e.y-pos.y)<c.range/3.1;});if(!targets.length)return;if(c.id==='haaselia'){targets.forEach(e=>hit(e,unitPower(u)*.56,u));burst(50,48,'#9cf2ff');}else{const target=targets.sort((a,b)=>b.y-a.y)[0];shoot(u,target,unitPower(u));}});}
function slotPosition(slot){const row=Math.floor(slot/3),col=slot%3;return{x:18+col*32,y:27+row*22};}
function shoot(u,target,power){const from=slotPosition(u.slot);const p=document.createElement('i');p.className='projectile';p.style.setProperty('--shot',u.character.orb);projectileLayer.append(p);const start=performance.now();function fly(now){const t=Math.min(1,(now-start)/210);p.style.left=(from.x+(target.x-from.x)*t)+'%';p.style.top=(from.y+(target.y-from.y)*t)+'%';if(t<1&&state.enemies.includes(target))requestAnimationFrame(fly);else{p.remove();if(state.enemies.includes(target))hit(target,power,u);}}requestAnimationFrame(fly);}
function hit(e,power,u){e.hp-=power;e.el.querySelector('i').style.width=Math.max(0,e.hp/e.maxHp*100)+'%';e.el.style.transform='scale(1.15)';setTimeout(()=>e.el&&(e.el.style.transform=''),80);if(e.hp<=0)destroyEnemy(e,true);}
function destroyEnemy(e,reward){e.el.remove();state.enemies=state.enemies.filter(x=>x!==e);if(reward){state.kills++;state.mana+=e.reward;currency();burst(e.x,e.y,e.boss?'#ffcd62':'#f7b9ff');}if(!state.spawnQueue.length&&!state.enemies.length&&state.wave<stages[state.stage].waves)setTimeout(startWave,900);else if(!state.spawnQueue.length&&!state.enemies.length&&state.wave===stages[state.stage].waves)victory();updateHud();}
function damageBase(n){state.base=Math.max(0,state.base-n);if(state.base<=0)gameOver();updateHud();}function burst(x,y,color){const p=document.createElement('i');p.className='projectile';p.style.cssText=`left:${x}%;top:${y}%;--shot:${color};width:20px;height:20px;opacity:.95;transition:.35s;`;projectileLayer.append(p);requestAnimationFrame(()=>{p.style.transform='scale(3)';p.style.opacity='0'});setTimeout(()=>p.remove(),400)}
function updateHud(){const s=stages[state.stage];$('stageName').textContent=s.name;$('wave').textContent=state.wave;$('waveMax').textContent=s.waves;$('kills').textContent=state.kills;$('enemiesLeft').textContent=state.enemies.length+state.spawnQueue.length;$('baseHp').textContent=Math.ceil(state.base);$('baseBar').style.width=state.base+'%';}
function notice(t){const n=$('waveNotice');n.textContent=t;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),1100)}function hint(t){$('hint').textContent=t}
function victory(){if(state.stageWon)return;state.stageWon=true;save();const next=state.stage<2;$('modalCard').innerHTML=`<h2>STAGE CLEAR!</h2><p>撃破数：${state.kills}<br>空の守りを貫きました！</p><button id="nextStage">${next?'次のステージへ':'もう一度遊ぶ'}</button>`;$('modal').classList.remove('hidden');$('nextStage').onclick=()=>reset(next?state.stage+1:0);}
function gameOver(){state.running=false;$('modalCard').innerHTML='<h2>拠点陥落…</h2><p>合成で高い★を作るほど、押し寄せる敵を一掃できます。</p><button id="retry">リトライ</button>';$('modal').classList.remove('hidden');$('retry').onclick=()=>reset(state.stage);}
function reset(stage){state.stage=stage;state.wave=0;state.mana=0;state.base=100;state.kills=0;state.units.forEach(u=>u.el.remove());state.enemies.forEach(e=>e.el.remove());state.units=[];state.enemies=[];state.spawnQueue=[];state.selected=[];state.summonCount=0;state.running=true;state.stageWon=false;closeModal();currency();updateHud();notice('BATTLE START');setTimeout(startWave,700);}
function loop(now){const dt=now-state.last;state.last=now;if(state.running&&!state.paused){updateEnemies(dt);attack(dt);refreshUnits();}requestAnimationFrame(loop)}
$('summonBtn').onclick=()=>{const free=slots.findIndex(s=>!state.units.some(u=>u.slot===+s.dataset.slot));if(free<0){hint('盤面が満員です。2体を選んで合成しよう！');return}makeUnit(free);};$('pauseBtn').onclick=()=>{state.paused=!state.paused;$('pauseBtn').textContent=state.paused?'▶':'Ⅱ';hint(state.paused?'一時停止中':'戦闘再開！')};setupBoard();guide();currency();updateHud();reset(0);requestAnimationFrame(loop);
